name: Build Game

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsdl2-dev libgl1-mesa-dev libgles2-mesa-dev

    - name: Compile Game
      run: |
        g++ DinoGame3D.cpp -o dino_game -lSDL2 -lGLESv1_CM -lGL

    - name: Upload Game Executable
      uses: actions/upload-artifact@v4
      with:
        name: DinoGame-Linux-Build
        path: dino_game
